// Exercise the actual browser formatter without a browser or new dependency.
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const root=path.resolve(__dirname,'..'),app=fs.readFileSync(path.join(root,'assets/app.js'),'utf8');
const context={};vm.createContext(context);
vm.runInContext(app.split('\n').filter(l=>/^const (\$|labels=|styles=|pretty=)/.test(l)).join('\n')+'\n'+app.slice(app.indexOf('function tags'),app.indexOf('function render'))+'\n'+app.slice(app.indexOf('function fields'),app.indexOf('async function openSource')),context);
const format=(...args)=>context.estimate(...args);
const escapeText=vm.runInContext('esc',context);
assert.equal(context.tableNumber('9.87973152'),'9.88');
assert.equal(context.tableNumber('199.6'),'199.60');
assert.equal(context.tableNumber('0'),'0.00');
assert.equal(context.tableNumber(''),'—');
assert.equal(context.tableNumber(null),'—');
assert.match(format('91.3424377','0.13150020','0.12361910','','','pc'),/^91\.34.*asymmetric-error.*\+0\.12.*−0\.13.* pc$/);
assert.equal(format('42.7','0.2','0.2','','','G'),'42.7 ± 0.2 G');
assert.equal(format('0','0','0','','','G'),'0 ± 0 G');
assert.match(format('1','', '0.2'),/minus unreported/);
assert.match(format('4','','','0','8'),/interval \[0, 8\]/);
assert.match(format('9.87973152','4.8e-9','4.8e-9','','','h'),/± 4\.8 × 10<sup>−9<\/sup> h/);
assert.equal(format('<img onerror=bad>','','','',''), '&lt;img onerror=bad&gt;');
const catalog=JSON.parse(fs.readFileSync(path.join(root,'assets/catalog.json'))),before=JSON.stringify(catalog);
const sections=['Source overview','Selected properties & periods','CMD placement','Radio observations','Evidence & references'];
const observationLabels=['Band','Reported flux or limit','Observable','Radio evidence','Uncertainty','Reference'];
for(const x of catalog.systems){
 const d=JSON.parse(fs.readFileSync(path.join(root,'assets/sources',x.token+'.json'))),original=JSON.stringify(d),html=context.sourceDetail(d,x);
 assert.deepEqual(Array.from(html.matchAll(/<h3>([^<]+)<\/h3>/g),m=>m[1]),sections);
 assert(!/NaN|undefined/.test(html),x.summary.source_name);
 assert.equal((html.match(/class="radio-row"/g)||[]).length,d.observations.length);
 for(const row of html.matchAll(/<dl class="raw-fields observation-summary">(.*?)<\/dl>/g))assert.deepEqual(Array.from(row[1].matchAll(/<dt>([^<]+)<\/dt>/g),m=>m[1]),observationLabels);
 assert(!/<details[^>]*\sopen(?:\s|>)/.test(html),'Evidence should start collapsed');
 for(const r of d.measurements)assert.equal(html.split('id="'+r.measurement_id+'"').length-1,1,r.measurement_id);
 for(const r of d.references)assert(html.includes(escapeText(r.key)));
 assert(html.includes('Unresolved issues & review history'));
 assert.equal(JSON.stringify(d),original,'Presentation must not mutate source data');
}
const added=catalog.systems.find(x=>x.summary.source_name==='ASKAP J144834-685644');
const addedData=JSON.parse(fs.readFileSync(path.join(root,'assets/sources',added.token+'.json')));
const addedHTML=context.sourceDetail(addedData,added);
assert.match(addedHTML,/No selected Gaia counterpart/);assert.match(addedHTML,/Main CMD: excluded/);
assert.match(addedHTML,/68% credible/);assert.match(addedHTML,/Radio recurrence period/);
const empty=JSON.parse(JSON.stringify(addedData));
for(const key of Object.keys(empty.summary))if(key.startsWith('preferred_'))empty.summary[key]='';
empty.observations[0].radio_band_ghz_as_reported='';empty.observations[0].flux_quantity_kind='Missing';
const emptyHTML=context.sourceDetail(empty,added);
assert(!emptyHTML.includes('class="property"'));assert.match(emptyHTML,/No selected physical properties or periods/);
assert.match(emptyHTML,/<dt>Band<\/dt><dd>Not reported<\/dd>/);assert.match(emptyHTML,/<dt>Reported flux or limit<\/dt><dd>Not selected\/reported<\/dd>/);
const ar=catalog.systems.find(x=>x.summary.source_name==='AR Sco').summary;
assert.match(context.propertyOverview(ar),/MCSE/);assert.match(context.propertyOverview(ar),/15 MG/);
assert.equal(JSON.stringify(catalog),before);
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
assert(!html.includes('SCIENTIFIC CATALOG'));assert(!html.includes('data-sort="white_dwarf_host_confidence"'));
assert(html.includes('id="additional-downloads"'));assert(!html.includes('id="additional-downloads" open'));
assert(html.includes('id="host"'));assert(html.includes('assets/logo.svg'));
console.log('PASS: 58 source details share section order and observation labels; evidence IDs, references, collapsed disclosures, exclusions, error conventions and unchanged data preserved.');
